---
build: off
image: ubuntu
stack: go 1.11

test_script:
  - mkdir -p $GOPATH/src/github.com/$APPVEYOR_REPO_NAME
  - cp -R ./* $GOPATH/src/github.com/$APPVEYOR_REPO_NAME/
  - cd $GOPATH/src/github.com/$APPVEYOR_REPO_NAME
  - make unit
