---
# See: https://hub.docker.com/r/panubo/sshd
version: "3.1"
services:
  rexecd:
    build:
      dockerfile: docker/builds/rexecd/Dockerfile
      context: ../
    ports:
      - "9000:9000"
    volumes:
      - "../:/go/src/github.com/metal-go/metal"
    environment:
      - METAL_LOG_LEVEL=debug
      - METAL_REXECD_DATA_SOURCE_NAME=root:password@tcp(docker_db_1:3306)/
      - METAL_REXECD_SERVER_TYPE=mysql
      - METAL_REXECD_KAFKA_VERSION=2.1.0
      - METAL_REXECD_KAFKA_ADDRESS=kafka:9092
    depends_on:
      - db
      - kafka
      - zoo

  rexecd_api:
    build:
      dockerfile: docker/builds/rexecd/Dockerfile
      context: ../
    command: /cmd api
    ports:
      - 8080:8080
    volumes:
      - "../:/go/src/github.com/metal-go/metal"
    environment:
      - METAL_LOG_LEVEL=debug
      - METAL_REXECD_DATA_SOURCE_NAME=root:password@tcp(docker_db_1:3306)
      - METAL_REXECD_KAFKA_VERSION=2.1.0
      - METAL_REXECD_KAFKA_ADDRESS=kafka=9092
    depends_on:
      - db
      - kafka
      - zoo

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    stdin_open: true
    tty: true

  host01:
    image: panubo/sshd
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys

  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zoo
    expose:
      - 9092

  zoo:
    image: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
