// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rexecd.proto

package rexecd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterHostRequest struct {
	Fqdn                 string   `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterHostRequest) Reset()         { *m = RegisterHostRequest{} }
func (m *RegisterHostRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterHostRequest) ProtoMessage()    {}
func (*RegisterHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a97cdcf024307f, []int{0}
}

func (m *RegisterHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterHostRequest.Unmarshal(m, b)
}
func (m *RegisterHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterHostRequest.Marshal(b, m, deterministic)
}
func (m *RegisterHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterHostRequest.Merge(m, src)
}
func (m *RegisterHostRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterHostRequest.Size(m)
}
func (m *RegisterHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterHostRequest proto.InternalMessageInfo

func (m *RegisterHostRequest) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *RegisterHostRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *RegisterHostRequest) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *RegisterHostRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type HostConnect struct {
	Fqdn                 string   `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostConnect) Reset()         { *m = HostConnect{} }
func (m *HostConnect) String() string { return proto.CompactTextString(m) }
func (*HostConnect) ProtoMessage()    {}
func (*HostConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a97cdcf024307f, []int{1}
}

func (m *HostConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostConnect.Unmarshal(m, b)
}
func (m *HostConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostConnect.Marshal(b, m, deterministic)
}
func (m *HostConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostConnect.Merge(m, src)
}
func (m *HostConnect) XXX_Size() int {
	return xxx_messageInfo_HostConnect.Size(m)
}
func (m *HostConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_HostConnect.DiscardUnknown(m)
}

var xxx_messageInfo_HostConnect proto.InternalMessageInfo

func (m *HostConnect) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *HostConnect) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type RegisterHostResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterHostResponse) Reset()         { *m = RegisterHostResponse{} }
func (m *RegisterHostResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterHostResponse) ProtoMessage()    {}
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a97cdcf024307f, []int{2}
}

func (m *RegisterHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterHostResponse.Unmarshal(m, b)
}
func (m *RegisterHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterHostResponse.Marshal(b, m, deterministic)
}
func (m *RegisterHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterHostResponse.Merge(m, src)
}
func (m *RegisterHostResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterHostResponse.Size(m)
}
func (m *RegisterHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterHostResponse proto.InternalMessageInfo

func (m *RegisterHostResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RegisterUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Admin                bool     `protobuf:"varint,4,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a97cdcf024307f, []int{3}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterUserRequest) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type RegisterUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a97cdcf024307f, []int{4}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

type CommandRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cmd                  string            `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Username             string            `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey           []byte            `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	HostConnect          []*HostConnect    `protobuf:"bytes,5,rep,name=host_connect,json=hostConnect,proto3" json:"host_connect,omitempty"`
	Env                  map[string]string `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Distribute           bool              `protobuf:"varint,8,opt,name=distribute,proto3" json:"distribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a97cdcf024307f, []int{5}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommandRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *CommandRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CommandRequest) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *CommandRequest) GetHostConnect() []*HostConnect {
	if m != nil {
		return m.HostConnect
	}
	return nil
}

func (m *CommandRequest) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *CommandRequest) GetDistribute() bool {
	if m != nil {
		return m.Distribute
	}
	return false
}

type CommandResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stdout               []byte   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte   `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExitCode             int64    `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5a97cdcf024307f, []int{6}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommandResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *CommandResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *CommandResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CommandResponse) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *CommandResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterHostRequest)(nil), "rexecd.RegisterHostRequest")
	proto.RegisterType((*HostConnect)(nil), "rexecd.HostConnect")
	proto.RegisterType((*RegisterHostResponse)(nil), "rexecd.RegisterHostResponse")
	proto.RegisterType((*RegisterUserRequest)(nil), "rexecd.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "rexecd.RegisterUserResponse")
	proto.RegisterType((*CommandRequest)(nil), "rexecd.CommandRequest")
	proto.RegisterMapType((map[string]string)(nil), "rexecd.CommandRequest.EnvEntry")
	proto.RegisterType((*CommandResponse)(nil), "rexecd.CommandResponse")
}

func init() { proto.RegisterFile("rexecd.proto", fileDescriptor_a5a97cdcf024307f) }

var fileDescriptor_a5a97cdcf024307f = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xad, 0xe3, 0x24, 0x4d, 0x26, 0x51, 0x7f, 0x3f, 0x6d, 0xab, 0x60, 0xa5, 0x85, 0x46, 0x3e,
	0xa0, 0x9c, 0x22, 0x28, 0xa2, 0x42, 0x1c, 0xb8, 0x44, 0x95, 0x90, 0x22, 0x38, 0xac, 0xc4, 0x39,
	0x72, 0xbc, 0xd3, 0x74, 0x45, 0xec, 0x75, 0x77, 0xd7, 0x51, 0x73, 0xe0, 0xc4, 0xa7, 0xe1, 0xca,
	0x47, 0xe2, 0x93, 0xa0, 0xfd, 0xe3, 0xc6, 0xf9, 0x73, 0xe0, 0xb6, 0xf3, 0x66, 0x77, 0xe6, 0xcd,
	0xbc, 0x67, 0x43, 0x5f, 0xe2, 0x13, 0xa6, 0x6c, 0x52, 0x48, 0xa1, 0x05, 0x69, 0xbb, 0x28, 0xfe,
	0x01, 0xe7, 0x14, 0x97, 0x5c, 0x69, 0x94, 0x9f, 0x85, 0xd2, 0x14, 0x1f, 0x4b, 0x54, 0x9a, 0x10,
	0x68, 0xde, 0x3f, 0xb2, 0x3c, 0x0a, 0x46, 0xc1, 0xb8, 0x4b, 0xed, 0xd9, 0x60, 0x85, 0x90, 0x3a,
	0x6a, 0x38, 0xcc, 0x9c, 0xc9, 0x35, 0xf4, 0x0a, 0xc9, 0xd7, 0x89, 0xc6, 0xf9, 0x77, 0xdc, 0x44,
	0xe1, 0x28, 0x18, 0xf7, 0x29, 0x78, 0x68, 0x86, 0x1b, 0xf2, 0x12, 0xa0, 0x28, 0x17, 0x2b, 0x9e,
	0xda, 0x7c, 0xd3, 0xe6, 0xbb, 0x0e, 0x99, 0xe1, 0x26, 0x7e, 0x0f, 0x3d, 0xd3, 0x76, 0x2a, 0xf2,
	0x1c, 0xd3, 0x7f, 0x6e, 0x1b, 0xbf, 0x86, 0x8b, 0x5d, 0xd6, 0xaa, 0x10, 0xb9, 0x42, 0x72, 0x06,
	0x0d, 0xce, 0xec, 0xeb, 0x90, 0x36, 0x38, 0x8b, 0x7f, 0x06, 0xdb, 0xf1, 0xbe, 0x29, 0x94, 0xd5,
	0x78, 0x43, 0xe8, 0x94, 0x0a, 0x65, 0x9e, 0x64, 0xe8, 0x7b, 0x3d, 0xc7, 0x86, 0xf1, 0x3d, 0x97,
	0x4a, 0xcf, 0x6d, 0xd6, 0x75, 0xed, 0x5a, 0xe4, 0xab, 0x49, 0x5f, 0x42, 0x77, 0x95, 0x54, 0xd9,
	0xd0, 0xbd, 0x35, 0x80, 0x4d, 0x5e, 0x40, 0x2b, 0x61, 0x19, 0xcf, 0xed, 0xa0, 0x1d, 0xea, 0x82,
	0x78, 0xb0, 0x65, 0xeb, 0x48, 0x38, 0xb6, 0xf1, 0xef, 0x06, 0x9c, 0x4d, 0x45, 0x96, 0x25, 0x39,
	0xab, 0x88, 0xed, 0x0d, 0x40, 0xfe, 0x87, 0x30, 0xcd, 0x98, 0x67, 0x61, 0x8e, 0x3b, 0xd4, 0xc3,
	0x3d, 0xea, 0x7b, 0x6a, 0x34, 0x0f, 0xd4, 0xb8, 0x85, 0xfe, 0x83, 0x50, 0x7a, 0x9e, 0xba, 0x7d,
	0x47, 0xad, 0x51, 0x38, 0xee, 0xdd, 0x9c, 0x4f, 0xbc, 0x35, 0x6a, 0x52, 0xd0, 0xde, 0x43, 0x4d,
	0x97, 0xb7, 0x10, 0x62, 0xbe, 0x8e, 0x4e, 0xed, 0xf5, 0xeb, 0xea, 0xfa, 0x2e, 0xf7, 0xc9, 0x5d,
	0xbe, 0xbe, 0xcb, 0xb5, 0xdc, 0x50, 0x73, 0x97, 0xbc, 0x02, 0x60, 0x5c, 0x69, 0xc9, 0x17, 0xa5,
	0xc6, 0xa8, 0x63, 0xf7, 0x51, 0x43, 0x86, 0xb7, 0xd0, 0xa9, 0x1e, 0x98, 0x29, 0x0d, 0x5f, 0xa7,
	0x84, 0x39, 0x9a, 0x45, 0xae, 0x93, 0x55, 0x59, 0xed, 0xdf, 0x05, 0x1f, 0x1b, 0x1f, 0x82, 0xf8,
	0x57, 0x00, 0xff, 0x3d, 0x37, 0x3e, 0x2e, 0x3b, 0x19, 0x40, 0x5b, 0x69, 0x26, 0x4a, 0x67, 0x9a,
	0x3e, 0xf5, 0x91, 0xc7, 0x51, 0x4a, 0x6f, 0x54, 0x1f, 0x91, 0x2b, 0xe8, 0x6a, 0x9e, 0xa1, 0xd2,
	0x49, 0x56, 0xd8, 0xad, 0x85, 0x74, 0x0b, 0x18, 0xc5, 0xf1, 0x89, 0x9b, 0xa5, 0x31, 0x8c, 0x5a,
	0x36, 0xdb, 0x31, 0xc0, 0x54, 0x30, 0x6b, 0x07, 0x94, 0x52, 0xc8, 0x79, 0xa6, 0x96, 0x51, 0xdb,
	0xe9, 0x61, 0x81, 0x2f, 0x6a, 0x79, 0xf3, 0x27, 0x80, 0x36, 0xb5, 0xbb, 0x22, 0x9f, 0xe0, 0xd4,
	0xb3, 0x26, 0x83, 0xe3, 0xfb, 0x1b, 0xbe, 0x38, 0xc0, 0xbd, 0x4f, 0x4e, 0xde, 0x04, 0x64, 0x06,
	0xfd, 0xba, 0xe3, 0xc9, 0x65, 0x75, 0xf9, 0xc8, 0xd7, 0x3b, 0xbc, 0x3a, 0x9e, 0xac, 0xca, 0xd5,
	0x8b, 0x19, 0x43, 0x1e, 0x16, 0xab, 0x7d, 0x2b, 0x87, 0xc5, 0x76, 0x3c, 0x7c, 0xb2, 0x68, 0xdb,
	0x1f, 0xca, 0xbb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x55, 0xea, 0x1f, 0x17, 0x60, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RexecdClient is the client API for Rexecd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RexecdClient interface {
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (Rexecd_CommandClient, error)
	RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
}

type rexecdClient struct {
	cc *grpc.ClientConn
}

func NewRexecdClient(cc *grpc.ClientConn) RexecdClient {
	return &rexecdClient{cc}
}

func (c *rexecdClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (Rexecd_CommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Rexecd_serviceDesc.Streams[0], "/rexecd.Rexecd/Command", opts...)
	if err != nil {
		return nil, err
	}
	x := &rexecdCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Rexecd_CommandClient interface {
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type rexecdCommandClient struct {
	grpc.ClientStream
}

func (x *rexecdCommandClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rexecdClient) RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error) {
	out := new(RegisterHostResponse)
	err := c.cc.Invoke(ctx, "/rexecd.Rexecd/RegisterHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rexecdClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/rexecd.Rexecd/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RexecdServer is the server API for Rexecd service.
type RexecdServer interface {
	Command(*CommandRequest, Rexecd_CommandServer) error
	RegisterHost(context.Context, *RegisterHostRequest) (*RegisterHostResponse, error)
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
}

func RegisterRexecdServer(s *grpc.Server, srv RexecdServer) {
	s.RegisterService(&_Rexecd_serviceDesc, srv)
}

func _Rexecd_Command_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RexecdServer).Command(m, &rexecdCommandServer{stream})
}

type Rexecd_CommandServer interface {
	Send(*CommandResponse) error
	grpc.ServerStream
}

type rexecdCommandServer struct {
	grpc.ServerStream
}

func (x *rexecdCommandServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Rexecd_RegisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RexecdServer).RegisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rexecd.Rexecd/RegisterHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RexecdServer).RegisterHost(ctx, req.(*RegisterHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rexecd_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RexecdServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rexecd.Rexecd/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RexecdServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rexecd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rexecd.Rexecd",
	HandlerType: (*RexecdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHost",
			Handler:    _Rexecd_RegisterHost_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _Rexecd_RegisterUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Command",
			Handler:       _Rexecd_Command_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rexecd.proto",
}
