#!/usr/bin/env bash

set -e

app_bundle="$(tar czf - app/dist 2> /dev/null | base64)"
if [[ ! -d "apploader/static" ]]; then mkdir -p "apploader/static"; fi

cat <<EOF > apploader/static/static.go
package static
var Bundle = "$app_bundle"
EOF

ldflags="-X \"github.com/metal-go/metal/cmd.Version=$(cat VERSION)\""
go install -ldflags "$ldflags"
